sudo: required

language: php

notifications:
  email: false

php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'

services:
- docker

cache:
  apt: true
  directories:
  - vendor
  - $HOME/.composer/cache/files

addons:
  browserstack:
    username: "johannalucie1"
    access_key:
      secure: "iaXId/+z21s+189Tg9BuN8CBun9qHtLfOj/S2XAAwsxw0b2fUQfg1AlKBp2UHHzAcqumTwhoWCiMkSZ71150h4SNv0UPsmKe5F1tm55kbQy8vKSXsOxaDkfMGVNVZcDJ8eNwiYtQH6tBgE7cdf4dzcWzK1MXX/x/tkLvvodkaf4iCloSmVKBSluGGMYWcdLUIAgl9CySYW6ZfmIU+0kssCQbP0CK/ulmHAZrHtuivpNiVOYJNDxBl8wGdmmtKeRViFyFijVvdMnzkkyImrG3TdAr74prbwUzkJT01C9yI7k0uZM7pzsuW8V6yTWJG0a1Z8+mo79hKBLAgVkJ5l88c0Cxfpq2/+BvrfW5qKqlA2qo56zvK4djj5GrfqHrxpdmTDa3ArxcLvmM9vULOeJqlGpdAlQw31mPcD+xDKIu7BPvjbf5X0SEPS8a25yVaqixLjg6tD+wH5C2ZEW9/4GYYaIlxicRYEfMwzS2YWD1HTbxHINScywpMkAe65CazNiJPVy3zHfMlfvCCFnA9ZqxuaZG7VaAp5ZkH3StJzG6hzj/yGdmmhftGyqB+jybuOFPxRf/j9CjKhC+m0NjBbPUcfg/uRw4L0PIzrEW5JieW8lNC/3Kp0YpiviFlgSRXzWyT/oVmgctCCLB/LDn0pMXwXwwK207WgYyLHN1Q9bYs70="
env:
  global:
  - WP_FOLDER="/wordpress"
  - WP_URL="http://bea-sanitize-filename.lndo.site"
  - WP_DOMAIN="bea-sanitize-filename.lndo.site"
  - DB_NAME="wordpress"
  - TEST_DB_NAME="wpTests"
  - WP_TABLE_PREFIX="wp_"
  - WP_ADMIN_USERNAME="admin"
  - WP_ADMIN_PASSWORD="admin"
  matrix:
  - WP_VERSION=latest
  - WP_VERSION=nightly
  - WP_VERSION=4.8.6
  - WP_VERSION=4.7.10
  - WP_VERSION=4.6.11
  - WP_VERSION=4.5.14
  - WP_VERSION=4.4.15

before_install:
- sudo apt-get -y update
- sudo apt-get -y install cgroup-bin curl
- curl -L -o /tmp/lando-latest.deb https://github.com/lando/lando/releases/download/v3.0.0-rc.1/lando-v3.0.0-rc.1.deb
- sudo dpkg -i /tmp/lando-latest.deb
- lando version
- phpenv version-name
- WP_VERSION=$WP_VERSION WP_LOCALE=en_US PHP_VERSION=$(phpenv version-name) ./bin/lando-start.sh
- lando info

script:
- true
- lando test