sudo: required

language: php

notifications:
  email: false

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

services:
  - docker

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache/files

env:
  global:
    - WP_FOLDER="/wordpress"
    - WP_URL="http://bea-sanitize-filename.lndo.site"
    - WP_DOMAIN="bea-sanitize-filename.lndo.site"
    - DB_NAME="wordpress"
    - TEST_DB_NAME="wploader"
    - WP_TABLE_PREFIX="wp_"
    - WP_ADMIN_USERNAME="admin"
    - WP_ADMIN_PASSWORD="admin"
  matrix:
    - WP_VERSION=latest
    - WP_VERSION=nightly
    - WP_VERSION=4.8.6
    - WP_VERSION=4.7.10
    - WP_VERSION=4.6.11
    - WP_VERSION=4.5.14
    - WP_VERSION=4.4.15

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install cgroup-bin curl
  - curl -L -o /tmp/lando-latest.deb https://github.com/lando/lando/releases/download/v3.0.0-rc.1/lando-v3.0.0-rc.1.deb
  - sudo dpkg -i /tmp/lando-latest.deb
  - lando version
  - ./bin/lando-start.sh $WP_VERSION fr_FR $(phpenv version-name)
  - lando launch-browserstack -k $BROWSERSTACK_KEY &

script:
  - true
  - lando test