sudo: required

language: php

notifications:
  email: false

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

services:
  - docker

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache/files

addons:
  browserstack:
    username: $BROWSERSTACK_USER
    access_key:
      secure: "Thke1u03rlX68wf4QN+RX1wa/mmXfB9sTDrRYRx65wgXWSRgpsg53U/Xpbuold5m7DTZ5mDYe9qRVrgBNwAofS1Wn+ihP2kvbc6XR8wrGJP/e8uz+zvrw5q+R0JE9sIhAQqb7SyIjHh0PWyZjpnMl69eT9p9jMttRpgW0EHQEZj31wBz3PFMV5OLQW6jndQ3QRf0YNHcri3tjL3keL6cFzEfQL+3S8g7kvvz4vghV4avoXuwMA4BL3flmYL9dgZ/fgDMrhQ7lLzCxj/6Gc5HOfvNwOU0Z78835n3zq0iWvdtDUw0TGuJMluiOr4W6KUf6le720kxC9cRc0YhUwrSNiEcoC6lUGJX6hNhiQUJSAjR7CckFrE4c8TyqYR6vqVz35xtq0LUoSa63pbRwyO/AZB/rPddysichxFGnxRBmVQFe+vLQIoe1x95PoPp8Fsf9d/G6h9XypncPBN7g1KG6w7CRLebpIYZQ1zPvpY5rEa4Hwz+fNFkKPGcssEh4lOfi/jk7O5+GALmoOTelcQiHY8qVnL3XsIiJEyTLlJxo1X7mcYk5u/Dbg2bXSMtrJojzCH5zflzrCgjOTiyiFzG668NeJ+DzSNXPaG42Xpj6+SuaLGetKeKZ53XlaYoK0Y2hhD0h3YfscFOwIHdO4MRpCebGeavgOVouvTgu4M6680="
    forcelocal: true
env:
  global:
    - WP_FOLDER="/wordpress"
    - WP_URL="http://bea-sanitize-filename.lndo.site"
    - WP_DOMAIN="bea-sanitize-filename.lndo.site"
    - DB_NAME="wordpress"
    - TEST_DB_NAME="wpTests"
    - WP_TABLE_PREFIX="wp_"
    - WP_ADMIN_USERNAME="admin"
    - WP_ADMIN_PASSWORD="admin"
  matrix:
    - WP_VERSION=latest
    - WP_VERSION=nightly
    - WP_VERSION=4.8.6
    - WP_VERSION=4.7.10
    - WP_VERSION=4.6.11
    - WP_VERSION=4.5.14
    - WP_VERSION=4.4.15

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install cgroup-bin curl
  - curl -L -o /tmp/lando-latest.deb https://github.com/lando/lando/releases/download/v3.0.0-rc.1/lando-v3.0.0-rc.1.deb
  - sudo dpkg -i /tmp/lando-latest.deb
  - lando version
  - phpenv version-name
  - ./bin/lando-start.sh $WP_VERSION fr_FR $(phpenv version-name)

script:
  - true
  - lando test