name: Tests

on: [pull_request]
jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: "Install PHP dependencies"
        run: composer install --no-interaction --prefer-dist

      - name: "Install Node.js dependencies"
        run: npm install

      - name: "Start wp-env"
        run: npm run wp-env:start

      - name: "Run unit tests"
        run: npm run test:unit

      - name: "Stop wp-env"
        if: always()
        run: npm run wp-env:stop